### ISSUE TITLE
Attach files option not availble in cake mail addin

### ISSUE THREAD

**Issue by VQuery** [cake-contrib/Cake.Email#16]
I am using Cake.Email addin for sending mail to multiple recipents but i need to attach some documents while sending mail.
I think we don't have this feature .So please add this option in Cake.Email addin .It will be very useful too

**Comment by Jericho** [comment]
I will add an additional parameter to the `SendEmail` method to accept an enumeration of attachments. Also, for convenience, there will be 2 new methods:
- CreateAttachmentFromLocalFile
- CreateAttachmentFromStream

**Comment by VQuery** [comment]
@Jericho  Thank you so much!!!!
