### ISSUE TITLE
MimeTypesMap is not included in the NuGet package

### ISSUE THREAD

**Issue by agc93** [cake-contrib/Cake.Email#20]
Currently, MimeTypesMap is not included in the NuGet package for Cake.Email. This results in a file not found assembly loading failure when running.

This would need any of:
- Including MimeTypesMap in the Nuget package (assuming Recipe can do this @gep13 ?)
- Try ILMerge/ILRepack'ing `MimeTypesMap.dll` into `Cake.Email.dll`
- ~~Update documentation to include `#nuget:?package=MimeTypesMap`~~ (wrong TFM)

**Comment by Jericho** [comment]
My bad, I forgot to add this DLL to the nuspec.
