### ISSUE TITLE
Given path format not supported 

### ISSUE THREAD

**Issue by VQuery** [cake-contrib/Cake.Email#22]
We could not use path format like below in LocalFile method 
```
var attachments = new[]
{
    Email.CreateAttachmentFromLocalFile("‪D:\\error.zip")
};
```
Error: The given path's format is not supported.

Tried like below

Email.CreateAttachmentFromLocalFile("‪./error.zip")

but shows

Error :Unble to locate local file

**Comment by Jericho** [comment]
You closed this issue so I'm assuming you figured out what the issue was. Right?

**Comment by VQuery** [comment]
Its working fine 
Email.CreateAttachmentFromLocalFile("./GitLog.Zip")
